### ISSUE TITLE
Use Case: Navigeren, NL-Begripp[enbibliotheek-GO

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/CB-NL#50]
CB-NL wil als eerste use case, het zoeken van begrippen in meerdere standaarden ondersteunen. Het zal daarom een termenlijst moeten hebben en links naar begrippen in andere standaarden. Niet meer, niet minder. Geen eigen definities. 

Deze use case moet beter worden beschreven

**Comment by ElisabethKloren** [comment]
In verband met de nieuwe werkwijze van DigiGO bij het publiceren van termen en definities wordt CB-NL niet verder ontwikkeld. De issues worden afgesloten.
