### ISSUE TITLE
Requirements in CB-NL en in Contracteisenspec

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/CB-NL#54]
We moeten even checken of de ontologie van de [Contractspecificaties](https://bimloket.github.io/contractspecificaties/) en CB-NL 2.0 overeenkomen als het gaat om specificaties en verificatiemethoden

**Comment by bartbink** [comment]
De CB-NL is een taxonomie met twee grote kenmerken:

- een class hiërarchie
- termen en definities

De CBNL heeft nog geen attributen toegekend aan concepten of relaties gelegd tussen concepten, zoals de relatie tussen een eis en een doel bijvoorbeeld. Qua termen zijn de CBNL en de Contractspecificaties minimaal vergelijkbaar en met een deel van de concepten overeenkomend.
