### ISSUE TITLE
Eisen aan Begrippenbibliotheek

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/CB-NL#59]
Voor de "Begrippenbibliotheek" graag uitwerken:

- Use case
- Eisen aan dataset
- Eisen aan viewer

**Comment by ElisabethKloren** [comment]
Uit het geaccepteerde advies van Semmtech: Wat te doen met de huidige versie van het ‘Woordenboek’ CB-NL?

- Beperk het beoogd gebruik van CB-NL tot gebruik voor het opvragen van begrippen (verwijzend naar bestaande definities uit bestaande bronnen).
- Noem het geen woordenboek, maar (bijvoorbeeld) ‘BegrippenBibliotheek-NL (voor de gebouwde omgeving)’, om niet de schijn van een volledige taal te wekken.
- Wat moet er technisch/functioneel gedaan worden:
- Beperk de ‘Begrippenlijst voor de gebouwde omgeving’ tot enkel de termen en hun verwijzingen naar definities in andere bronnen. 
- Gebruik de ‘scenario’s’ als mogelijke use cases van de begrippenlijst, en geef uitgewerkte voorbeelden van toepassingen mee.

**Comment by ElisabethKloren** [comment]
![image](https://github.com/bimloket/CB-NL/assets/48585720/d5f34a65-2434-4f8e-ada4-425840691ea3)

**Comment by ElisabethKloren** [comment]
1. Modelleer de bibliotheek conform de SKOS-stijl uit NEN 2660-2
2. Kies één naam in het Nederlands. Deze dient uitsluitend voor herkenbaarheid van het concept, Optioneel kan ook een Engelse naam toegevoegd worden
3. Gebruik een informele structuur. Hier dient geen waarde aan ontleend te worden; de enige functie is om eenvoudiger te navigeren door de bibliotheek indien gewenst.
4. Neem geen definities op van de concepten, deze kunnen in de externe bronnen gevonden worden.
5. Verwijder de uitwerkingen van de verschillende externe bronnen (IMBOR, NEN2767, etc.) en behoud alleen de links naar de termen in de betreffende standaarden

**Comment by ElisabethKloren** [comment]
![image](https://github.com/bimloket/CB-NL/assets/48585720/a91a206d-0513-4c9a-a2b8-0c3d42903eb4)

**Comment by ElisabethKloren** [comment]
1. Elke linkset (een set aan links tussen BB-NL en één andere standaard) wordt los gepubliceerd. Dit biedt als voordelen dat:

- (versie)beheer voor iedere linkset onafhankelijk van andere onderdelen blijft\
- gebruikers eenvoudig kunnen kiezen welke linksets ze willen toepassen

2. Gebruik voor de links een beperkt aantal opties; skos:closeMatch (zeer vergelijkbaar), skos:relatedMatch (enigszins vergelijkbaar), skos:narrowMatch (gelinkt begrip is specifieker), skos:broadMatch (gelinkt begrip is generieker).

3. De te linken standaard moet, net als BB-NL, conform de SKOS-stijl uit NEN 2660-2 gepubliceerd worden. Op deze manier wordt geborgd dat gebruikers/applicaties altijd dezelfde vraag (query) kunnen stellen en zeker zijn van hetzelfde resultaat. De SKOS-publicatie van IMBOR is hier een goed voorbeeld van.

- Bibliotheken die niet als Linked Data beschikbaar zijn kunnen dus ook niet gelinkt worden: het is niet mogelijk om deze uniform te bevragen, dus geen meerwaarde

**Comment by ElisabethKloren** [comment]
Een Use Case: BegrippenBibliotheek-NL gebruiken in een ILS-OTL

Benoem een beoogd gebruik: Als opdrachtgever van een nieuw kunstwerk wil ik kenmerken van het kunstwerk en zijn onderdelen, die nodig zijn om onderhoud, registreren in mijn onderhoudsprogramma Maximo. Daartoe wil ik van mijn opdrachtnemer de kenmerken digitaal aangeleverd krijgen bij oplevering van het kunstwerk. Daartoe zal ik met een OTL:

- eenduidig uitvragen welke informatie ik verwacht van welk onderdeel en in welk format.
- optioneel) kunnen herleiden welke begrippen bekend zijn in de sector.

Welke informatie heb ik nodig:

- Objecten
- Aspecten (intrinsieke kenmerken), gerelateerd aan de objecten
- Relaties naar (definities uit) standaardenHoe leg ik dit vast:
- Een objectenbibliotheek met formele (RDFS/SHACL) structuur, inclusief koppelingen tussen objecten en aspecten
- Verwijzingen naar een subset van begrippen uit de BegrippenBibliotheek-NL

**Comment by ElisabethKloren** [comment]
![image](https://github.com/bimloket/CB-NL/assets/48585720/9d6b1191-917b-4bf0-a255-67a470b4b808)

**Comment by ElisabethKloren** [comment]
Toelichting: 
- Wanneer een ILS-OTL wordt gemaakt bouwt deze verder op begrippen uit BegrippenBibliotheek-NL (door middel van een link, rdfs:seeAlso)
- Omdat de ILS-OTL verwijst naar de BegrippenBibliotheek-NL kan een gebruiker eenvoudig verwijzingen en definities van andere standaarden ophalen
- De ILS-OTL conformeert aan NEN 2660-2. Voor een ILS is formele logica nodig, dus wordt de RDFS/SHACL modelleer stijl gebruikt.

**Comment by ElisabethKloren** [comment]
### Viewer van de standaarden

CB-NL wil een gebruiksvriendelijke viewer (laten) ontwikkelen die kan worden geplaatst op de website van DigiGO met de volgende doelen: 

* Een eindgebruiker zonder technische kennis kan de begrippen uit standaarden in de gebouwde omgeving raadplegen en kan zoeken naar termen.  

* De standaarden worden ondersteund in het vergelijken van elkaars begrippen en om en definities op elkaar af te stemmen.  

* DigiGO kan een betere digitale publicatievorm van standaarden van partnerorganisaties promoten; het is immers direct een voordeel als je woordenboek vindbaar en doorzoekbaar wordt in samenhang met andere standaarden.  

* Als de broncode van de “zoekvragen” open gepubliceerd wordt, kunnen deze gebruikt worden door applicatiebouwers om de standaarden te ontsluiten binnen applicaties.

**Comment by ElisabethKloren** [comment]
Checkvraag: moeten we alle gepubliceerde termen in de andere standaarden overnemen?

~ idee: je moet kunnen zoeken of jou term ergens al gestandaardiseerd is

**Comment by ElisabethKloren** [comment]
Niels H heeft gemaild: Ik heb de stukken wel even bekeken en wil een ding mee geven voor het punt over de begrippenbibliotheek. Is dat namelijk niet voor een groot deel al de functionaliteit die BegrippenXL aanbiedt? Namelijk kunnen zoeken over verschillende gegevenswoordenboeken heen.
 
Het eventuele extra deel is relaties duiden tussen die verschillende begrippen. Maar dan moet je dus nadenken met welke ‘autoriteit’ je die relaties legt. Zijn dat relaties die gedefinieerd zijn door de experts van CB-NL, of gedragen door een community?

**Comment by ElisabethKloren** [comment]
NEN-ISO normen\25964 Thesauri

**Comment by ElisabethKloren** [comment]
In verband met de nieuwe werkwijze van DigiGO bij het publiceren van termen en definities wordt CB-NL niet verder ontwikkeld. De issues worden afgesloten.
