### ISSUE TITLE
controleren stylesheet

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/CB-NL#60]
Gerrit heeft de CB-NL zoals die nu in Laces staat gepubliceerd met de stylesheet, zodat het schema overeenkomt met het schema van de oorspronkelijke CB-NL. De publicatie is beschikbaar op [http://hub.laces.tech/digitalbuildingdata/cb-nl/live/cb-nl/versions/v0_2](https://eur02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fhub.laces.tech%2Fdigitalbuildingdata%2Fcb-nl%2Flive%2Fcb-nl%2Fversions%2Fv0_2&data=05%7C01%7Celisabeth.devries%40crow.nl%7Ccc9d3a905556420b7fe008db7b81be6f%7C1e0440a2a638433189c766de8119b255%7C0%7C0%7C638239569439538636%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8RxY0DkhhDiUSTDArQqTATW9AK2W4fgQ4PNw%2BFqwWj4%3D&reserved=0). Als jullie de publicatie willen controleren kan dat het beste door een kopie van de publicatie te downloaden, of via het SPARQL endpoint voor specifieke controles.

**Comment by ElisabethKloren** [comment]
In verband met de nieuwe werkwijze van DigiGO bij het publiceren van termen en definities wordt CB-NL niet verder ontwikkeld. De issues worden afgesloten.
