### ISSUE TITLE
Links naar viewer CB-NL 1.0

### ISSUE THREAD

**Issue by ElisabethDeVries** [nl-digigo/CB-NL#61]
gemeente Rotterdam maakt gebruik van de CBNL standaard echter de verwijzingen werken niet meer
Graag contact hierover

Ik krijg als voorbeeld deze melding

![image](https://github.com/nl-digigo/CB-NL/assets/48585720/b4ec803d-5394-4b68-a8ad-dbf644a2b0d8)

**Comment by ElisabethKloren** [comment]
Per mail beantwoord: 

In de afgelopen jaren is de NEN 2660-2 voor de gebouwde omgeving ontstaan, en is versie 1.0 van CB-NL omgezet naar een versie 2.0 die daar aan voldoet. Versie 2.0 van CB-NL is gepubliceerd op een sparql-endpoint. Er is een (niet zo mooie) viewer: [technische viewer CB-NL 2.0](https://nl-digigo.github.io/ld-viewer/cb-nl2.0-pilot/). Van CB-NL is hier alleen nog de 'CB-NL Def' ingeladen (en die importeert NEN2660-RDFS). 
De mooie viewer die bij versie 1.0 bestond, niet kon worden omgezet omdat het een heel andere datastructuur betreft. Dat is de viewer waar jij in onderstaande bericht naar toe linkte.

Het adres van het sparql-endpoint (de linked data publicatie van CB-NL 2.0) is: http://hub.laces.tech/digitalbuildingdata/cb-nl/live/cb-nl/versions/v0_2_1; daar kun je termen en definities uithalen.

Voor meer uitgebreide toelichting op CB-NL 2.0 kun je terecht op GitHub: https://github.com/nl-digigo/CB-NL, in de Readme staan links naar documentatie.

Tegelijkertijd is de afgelopen jaren het besef gegroeid, dat er niet “1 model voor de wereld” bestaat; zoiets als een “voorkeursdefinitie” voor een object klopt niet met het besef, dat een definitie afhangt van het gebruikersperspectief. Hoe relaties tussen standaarden gelegd worden, hangt af van het doel van hoe je standaarden wilt combineren. DigiGO is zich daarom gaan beraden op, hoe verder te gaan met CB-NL. De eerste stap is toch, om te zorgen dat alle standaarden hun eigen termen en definities gaan publiceren als linked open data, zodat er geen “centrale kopie” maar hoeft te worden gemaakt bij CB-NL.
